# Generated by Django 5.2.17 on 2026-08-30 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_delivered_at_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=14)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_detail', to='products.order')),
            ],
        ),
    ]
